### ISSUE TITLE
Firespitter.dll not loaded

### ISSUE THREAD

**Issue by Shaggygoblin** [net-lisias-ksp/ModuleManager#15]
Howdy, Lisias
Using [MM/L](https://github.com/net-lisias-ksp/ModuleManager) and the [Unleashed - Firespitter](https://github.com/net-lisias-kspu/Firespitter)
There's a warning that Firespitter.dll couldn't be loaded.
This results in a Reflection warning.

![Firespitter dll-not-loaded](https://user-images.githubusercontent.com/11417143/190835113-437936a7-2ba3-4ac7-94a3-b4f6971f2781.jpg)

![Reflection Warning](https://user-images.githubusercontent.com/11417143/190835206-3030e186-175e-4874-b408-21689210df60.jpg)

[Player.log](https://github.com/net-lisias-ksp/ModuleManager/files/9590721/Player.log)
[KSP.log](https://github.com/net-lisias-ksp/ModuleManager/files/9590722/KSP.log)

Will clean out and load up Cannon MM and see if same.

**Comment by Shaggygoblin** [comment]
Update:
Using the [Forum MM](https://ksp.sarbian.com/jenkins/job/ModuleManager/162/artifact/ModuleManager.4.2.2.dll) and the same [Unleashed - Firespitter](https://github.com/net-lisias-kspu/Firespitter)
I still get the Failed to load firespitter.dll error on the loading screen, but once I load the space center scene, there's no Reflection Warning.

![CanonMM-No-Reflection-Warning](https://user-images.githubusercontent.com/11417143/190836011-3474bdf4-1264-477f-9950-3e3f6647b9f3.jpg)

[KSP.log](https://github.com/net-lisias-ksp/ModuleManager/files/9590743/KSP.log)
[Player.log](https://github.com/net-lisias-ksp/ModuleManager/files/9590744/Player.log)


going to try with the [MM/L](https://github.com/net-lisias-ksp/ModuleManager) and [current Firespitter](https://github.com/snjo/Firespitter)

**Comment by Lisias** [comment]
The latest release for "my" firespitter is from 2019, it only works on the KSP until that date.

https://github.com/net-lisias-kspu/Firespitter/releases/tag/RELEASE%2F7.13.0.1

I think this one works only up to 1.7.3.

On the bottom line, Firespitter makes heavy use of Unity, and as Unity released new versions, some of the features Firespitter relies changed - even the ABI was broken between Major Unity Releases, screwing up Firespitter.

I have custom compilations with DLLs specific for KSP versions under Unity 5, under Unity 2017 and 2019  but never bothered to publish them.

I will see how to publish them as time allows.

**Comment by Shaggygoblin** [comment]
Seems to play fine with MM/L and the most recent Firespitter.dll.
So I'd say whatever's happening is in the older FS.dll.

**Comment by Lisias** [comment]
Forgot to close this! Doing it now!
