### ISSUE TITLE
4.2.2.4.zip structure seems broken + double .dll

### ISSUE THREAD

**Issue by Shaggygoblin** [net-lisias-ksp/ModuleManager#16]
@Lisias
The directory structure in the [4.2.2.4.zip](https://github.com/net-lisias-ksp/ModuleManager/releases/download/RELEASE%2F4.2.2.4/ModuleManager-4.2.2.4.zip) needs sorted.
The GameData folder contains the PluginData folder.
PluginData shouldn't be nested under GameData.  Given what you're trying to accomplish on the whole, I could be very wrong; I'm just an observer.
There are currently 2 ModuleManger.dll in this .zip as well, causing the double .dll warning in mini-avc.
As it is, if one drags GameData from the .zip to the ksp-root, it creates:
`.\ksp-root\GameData\ModuleManager.dll`
`.\ksp-root\GameData\ModuleManager\PluginData\ModuleManager.dll"`

Here's the corrected Directory:
[ModuleManager-4.2.2.4.zip](https://github.com/net-lisias-ksp/ModuleManager/files/9595447/ModuleManager-4.2.2.4.zip)
- GameData(dir)
  - Change_Log.md
  - LICENSE
  - ModuleManager.dll
  - ModuleManager.version
  - NOTICE
  - README.md
- PluginData(dir)
  - ModuleManager(dir)
- INSTALL.md

Cheers!

For giggles, this is what clued me into it being 'off':
![NeedMoreMM](https://user-images.githubusercontent.com/11417143/190932998-1cf6ccd5-9ff0-4008-821c-9ab11904a7a3.jpg)

I was Drag&Dropping from the .zip to the ksp-root, and was expecting it to overwrite/replace the current `...\GameData\ModuleManager.dll`
When presented with the confirm replace files, it didn't occur to me to look at the file count; it would have been one short.

**Comment by Lisias** [comment]
It's by design. The Zero Mini AVC is wrong.

DLLs on `PluginData` are ignored by KSP, and "ModuleManagerWatchDog" uses it as a reference to keep the DLL on GameData (the one that's effectively loaded), updated and intact.

Please ask Zero Mini AVC to update its code.

**Comment by Lisias** [comment]
Hummm… I forgot to update the INSTALL.md file!!!

**Comment by Lisias** [comment]
So, yeah. This work "works-as-intended" because the deployment model has changed and the current one is what things will be.

It's also "unrelated" because Zero Mini AVC is false flagging it as a problem.

But it's also a "bug" because I didn't updated the INSTALL.md file!

(Isn't Software Development such a Wonder?)

**Comment by Lisias** [comment]
A new 4.2.2.b release was issue with the `INSTALL.md` updated.

Since the only changes were the CHANGE_LOG and the INSTALL, I just shoved a "b" on the release name and called it a day.

https://github.com/net-lisias-ksp/ModuleManager/releases/tag/RELEASE%2F4.2.2.4b

**Comment by Shaggygoblin** [comment]
rgr, rgr!
